name: Python CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: pip install -r requirements.txt

      # Install Bandit
      - name: Install Bandit
        run: pip install bandit

      # Fetch Threat Intelligence Feeds
      - name: Fetch Threat Intelligence Feeds
        run: |
          wget https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz
          gunzip nvdcve-1.1-modified.json.gz

      # Analyze Threat Intelligence
      - name: Analyze Threat Intelligence
        id: analysis
        run: |
          python analyze_threat_intelligence.py nvdcve-1.1-modified.json

      # Conditional step for Bandit scan
      - name: Bandit Scan
        if: ${{ steps.analysis.outputs.total_xss_vulnerabilities < 50 && steps.analysis.outputs.total_authentication_bypass_vulnerabilities < 5 }}
        run: |
          bandit -r . -lll -iii

      # Run Bandit SAST scan
      - name: Run Bandit SAST scan
        run: bandit -r . -lll -iii

      # Fail if vulnerabilities found
      - name: Fail if vulnerabilities found
        if: steps.bandit.outputs.exit_code != 0
        run: |
          echo "Vulnerabilities found by Bandit! Stopping build."
          exit 1

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      # DockerHub login
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      # Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile 
          push: true
          tags: mdharshaprada/agrosage:latest

      # Docker Scout Scan
      - name: Docker Scout Scan
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
          docker scout quickview
          docker scout cves
